import { ROUTES } from '@/constants/routes'

import type { GroupRole, MemberDay } from '../api/groups-data'

/*
 * Pure Groups rules (spec §46–48). Informational only: nothing here ranks,
 * scores or compares members.
 */

export const groupPath = (groupId: string) => `${ROUTES.groups}/${groupId}`

/** Code alphabet generated by the database (no 0/O, 1/I/L). */
export const CODE_ALPHABET = 'ABCDEFGHJKMNPQRSTUVWXYZ23456789'
export const CODE_LENGTH = { min: 6, max: 12 } as const

/** Same normalisation as the server: case, spaces and dashes are ignored. */
export function normalizeGroupCode(raw: string): string {
  return raw.replace(/[\s-]/g, '').toUpperCase()
}

/** Shape check only; whether a group exists is always decided by the server. */
export function isPlausibleGroupCode(code: string): boolean {
  return (
    /^[A-Z0-9]+$/.test(code) && code.length >= CODE_LENGTH.min && code.length <= CODE_LENGTH.max
  )
}

/** "ABCD-EFGH": easier to read aloud and copy. */
export function formatGroupCode(code: string): string {
  return code.length === 8 ? `${code.slice(0, 4)}-${code.slice(4)}` : code
}

export const ROLE_LABELS: Record<GroupRole, string> = {
  ADMIN: 'Group admin',
  LEADER: 'Group leader',
  MEMBER: 'Member',
}

export interface GroupPermissions {
  canRemoveMembers: boolean
  canChangeRoles: boolean
  /** Leaders and admins see history from before they joined (spec §48). */
  hasExtendedHistory: boolean
}

export function permissionsFor(role: GroupRole): GroupPermissions {
  return {
    canRemoveMembers: role === 'ADMIN',
    canChangeRoles: role === 'ADMIN',
    hasExtendedHistory: role === 'ADMIN' || role === 'LEADER',
  }
}

export type LeaveOutcome =
  { kind: 'leave' } | { kind: 'last-member' } | { kind: 'needs-another-admin' }

/**
 * What leaving means for this user (the database enforces the same rule):
 * the only admin of a group with other members must appoint another admin
 * first; the last member leaving closes the group.
 */
export function leaveOutcome(
  myRole: GroupRole,
  members: readonly { role: GroupRole }[],
): LeaveOutcome {
  if (members.length <= 1) return { kind: 'last-member' }
  const admins = members.filter((member) => member.role === 'ADMIN').length
  if (myRole === 'ADMIN' && admins <= 1) return { kind: 'needs-another-admin' }
  return { kind: 'leave' }
}

export interface MetricView {
  /** Formatted actual value, or null when nothing was recorded. */
  actual: number | null
  /** Target shown only when one exists (never an invented 0). */
  target: number | null
}

export interface MemberCardView {
  calories: MetricView
  protein: MetricView
  steps: MetricView
  workout: 'done' | 'none'
  /** Nothing at all recorded for the day. */
  empty: boolean
}

const whole = (value: number | null) => (value === null ? null : Math.round(value))

/** The group-visible metrics of one member card. Missing stays missing. */
export function memberCardView(day: MemberDay): MemberCardView {
  const calories = { actual: whole(day.calories), target: day.caloriesTarget }
  const protein = { actual: whole(day.proteinG), target: whole(day.proteinTargetG) }
  const steps = { actual: day.steps, target: day.stepsTarget }
  return {
    calories,
    protein,
    steps,
    workout: day.workoutLogged ? 'done' : 'none',
    empty: day.calories === null && day.steps === null && !day.workoutLogged,
  }
}

const KNOWN_ERRORS: readonly [RegExp, string][] = [
  [/invalid group code/i, 'That code doesn’t match a group. Check it and try again.'],
  [/another member a group admin/i, 'Make another member a group admin before leaving.'],
  [/not a member/i, 'You’re no longer a member of this group.'],
  [/only a group admin/i, 'Only a group admin can do that.'],
  [/1–60 characters/i, 'The group name must be 1–60 characters.'],
]

/** User-facing text; never raw database messages. */
export function friendlyGroupError(error: unknown, fallback: string): string {
  if (error instanceof TypeError)
    return 'Couldn’t reach the server. Check your connection and try again.'
  const message =
    error && typeof error === 'object' && 'message' in error && typeof error.message === 'string'
      ? error.message
      : ''
  return KNOWN_ERRORS.find(([pattern]) => pattern.test(message))?.[1] ?? fallback
}
